<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class QuestionStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        //一般判断当前用户是否有权发送本实例的请求,先默认设置为true，不过可以先写一个判断当前用户是否是请求中的用户来判断返回值

        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     * 验证规则
     * @return array
     */
    public function rules()
    {
        return [
            //
            'title' => 'required|min:8',
            'content' => 'required|min:28',
        ];
    }

    /**
     * @return array
     */
    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        //错误提示
        return [
            'title.required' => '标题必须要输入的哦！',
            'title.min' => '标题长度要大于8个的哦！',
            'content.required' => '内容必须要输入的哦！',
            'content.min' => '内容长度必须要大于28个的哦！',
        ];
    }
}
